# Generated by Django 3.1.7 on 2021-03-09 12:21

import data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название города')),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название ограничения')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='образование')),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название фирмы')),
                ('discription', models.TextField(default=data.models.Firm.contact_default, verbose_name='описание фирмы')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название ключевого навыка')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='опыт')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='адрес')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('sex', models.IntegerField(blank=True, default=1, verbose_name='пол')),
                ('name1', models.CharField(blank=True, max_length=200, verbose_name='имя')),
                ('name2', models.CharField(blank=True, max_length=200, verbose_name='фамилия')),
                ('name3', models.CharField(blank=True, max_length=200, verbose_name='отчество')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.city')),
                ('disability', models.ManyToManyField(to='data.Disability')),
                ('education', models.ManyToManyField(to='data.Education')),
                ('skills', models.ManyToManyField(to='data.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название профессии')),
                ('description', models.TextField(default=data.models.Profession.contact_default, verbose_name='описание профессии')),
                ('disability', models.ManyToManyField(to='data.Disability')),
                ('education', models.ManyToManyField(to='data.Education')),
            ],
        ),
    ]
