# Generated by Django 3.1.7 on 2021-05-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desired_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='желаемая зарплата'),
        ),
    ]
