# Generated by Django 3.1.7 on 2021-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='disability_group',
        ),
        migrations.AlterField(
            model_name='workplace',
            name='liked_by_profile',
            field=models.ManyToManyField(blank=True, related_name='liked_by_profile', to='data.Profile', verbose_name='Пользователи которые лайкнули'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='profile_liked',
            field=models.ManyToManyField(blank=True, related_name='profile_liked', to='data.Profile', verbose_name='Пользователи лайкнутые работадателем'),
        ),
    ]
