# Generated by Django 3.1.7 on 2021-05-19 17:25

import data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=data.models.Course.contact_default, max_length=200, verbose_name='Название образовательной программы')),
                ('description', models.TextField(default=data.models.Course.contact_default, verbose_name='Описание образовательной программы')),
                ('count', models.IntegerField(null=True, verbose_name='Количество мест')),
                ('price', models.IntegerField(null=True, verbose_name='Стоимость обучения на 1 человека')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.profession', verbose_name='Компетенция')),
            ],
        ),
        migrations.AddField(
            model_name='workplace',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество рабочих мест'),
        ),
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование университета')),
                ('course', models.ManyToManyField(blank=True, to='data.Course', verbose_name='Курсы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
