# Generated by Django 3.1.7 on 2021-05-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210520_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='confirmed_profile',
            field=models.ManyToManyField(blank=True, related_name='confirmed_profile', to='data.Profile', verbose_name='Подтвержденные ученики'),
        ),
        migrations.AddField(
            model_name='course',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profile', to='data.Profile', verbose_name='Ученики'),
        ),
    ]
