# Generated by Django 3.1.7 on 2021-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210309_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(to='data.Profession'),
        ),
    ]
