# Generated by Django 3.1.7 on 2021-05-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210520_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='адрес'),
        ),
    ]
