# Generated by Django 3.1.7 on 2021-03-14 06:01

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_profile_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=data.models.WorkPlace.contact_default, max_length=200, verbose_name='Title work place')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.city')),
                ('disability', models.ManyToManyField(to='data.Disability')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.education')),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.firm')),
                ('profession', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.profession')),
            ],
        ),
    ]
