# Generated by Django 3.1.7 on 2021-05-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210522_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='skill',
            field=models.ManyToManyField(blank=True, to='data.Skill', verbose_name='компетенции'),
        ),
    ]
