# Generated by Django 3.1.7 on 2021-03-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_workplace_prof_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='тип занятости')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='график работы')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='опыт работы')),
            ],
        ),
        migrations.AddField(
            model_name='workplace',
            name='max_salary',
            field=models.IntegerField(null=True, verbose_name='максимальная зарплата'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='min_salary',
            field=models.IntegerField(null=True, verbose_name='минимальная зарплата'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='skill',
            field=models.ManyToManyField(blank=True, to='data.Skill', verbose_name='опыт работы'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='disability',
            field=models.ManyToManyField(blank=True, to='data.Disability', verbose_name='ограничения'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data.education', verbose_name='образование'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.firm', verbose_name='фирма'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.profession', verbose_name='профессия'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='employment_type',
            field=models.ManyToManyField(blank=True, to='data.EmploymentType', verbose_name='тип занятьости'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='data.Schedule', verbose_name='график работы'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='work_experience',
            field=models.ManyToManyField(blank=True, to='data.WorkExperience', verbose_name='опыт работы'),
        ),
    ]
