# Generated by Django 3.1.7 on 2021-03-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210314_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='workplace',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.workexperience', verbose_name='опыт работы'),
        ),
    ]
