# Generated by Django 3.1.7 on 2021-03-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20210314_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='profession',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.profession', verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='work_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='data.workexperience', verbose_name='опыт работы'),
        ),
    ]
