# Generated by Django 3.1.7 on 2021-03-15 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0009_auto_20210314_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='employment_type',
            field=models.ManyToManyField(blank=True, to='data.EmploymentType', verbose_name='тип занятости'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.profession', verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='skill',
            field=models.ManyToManyField(blank=True, to='data.Skill', verbose_name='навыки'),
        ),
    ]
