# Generated by Django 3.1.7 on 2021-03-15 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210315_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='disability',
            field=models.ManyToManyField(blank=True, to='data.Disability'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(blank=True, to='data.Education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(blank=True, to='data.Profession'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='data.Skill'),
        ),
    ]
