# Generated by Django 3.1.7 on 2021-04-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20210331_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkToWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Профессии1', to='data.profession')),
                ('profession', models.ManyToManyField(blank=True, related_name='Профессии', to='data.Profession')),
            ],
        ),
    ]
