# Generated by Django 3.1.7 on 2021-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_worktowork'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='boundProfession',
            field=models.ManyToManyField(blank=True, related_name='_profession_boundProfession_+', to='data.Profession'),
        ),
        migrations.DeleteModel(
            name='WorkToWork',
        ),
    ]
