# Generated by Django 3.1.7 on 2021-04-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20210416_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='boundProfession',
            field=models.ManyToManyField(blank=True, related_name='_profession_boundProfession_+', to='data.Profession', verbose_name='связанные профессии'),
        ),
    ]
