# Generated by Django 3.1.7 on 2021-04-24 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0019_auto_20210424_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='liked_by_profile',
            field=models.ManyToManyField(blank=True, related_name='liked_by_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи которые лайкнули'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='profile_liked',
            field=models.ManyToManyField(blank=True, related_name='profile_liked', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи лайкнутые работадателем'),
        ),
    ]
